# Generated by Django 3.1.5 on 2021-02-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='uname',
        ),
    ]
