# Generated by Django 3.1.5 on 2021-02-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210201_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='uname',
            new_name='username',
        ),
    ]
