# Generated by Django 3.1.5 on 2021-02-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210201_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
