# Generated by Django 3.1.5 on 2021-02-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20210208_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
