# Generated by Django 3.1.5 on 2021-03-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20210303_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
    ]
